// Generado automáticamente a partir del data.js original.
// No editar a mano — se usa una sola vez desde importar.html.
const IMPORT_CATEGORIES = [
  {
    "id": "alojamiento",
    "label": "Alojamiento",
    "icon": "🏨",
    "color": "#0ea5e9",
    "sort_order": 1
  },
  {
    "id": "gastronomia",
    "label": "Gastronomía",
    "icon": "🍽️",
    "color": "#f97316",
    "sort_order": 2
  },
  {
    "id": "turismo",
    "label": "Turismo",
    "icon": "📸",
    "color": "#16a34a",
    "sort_order": 3
  },
  {
    "id": "salud",
    "label": "Salud",
    "icon": "💙",
    "color": "#2563eb",
    "sort_order": 4
  },
  {
    "id": "comercios",
    "label": "Comercios",
    "icon": "🛍️",
    "color": "#db2777",
    "sort_order": 5
  },
  {
    "id": "servicios",
    "label": "Servicios",
    "icon": "🔧",
    "color": "#71717a",
    "sort_order": 6
  },
  {
    "id": "deportes",
    "label": "Deportes",
    "icon": "🏋️",
    "color": "#ca8a04",
    "sort_order": 7
  },
  {
    "id": "entretenimiento",
    "label": "Entretenimiento",
    "icon": "🎭",
    "color": "#7c3aed",
    "sort_order": 8
  }
];
const IMPORT_SUBCATEGORIES = [
  {
    "id": "resto",
    "category_id": "gastronomia",
    "label": "Resto",
    "sort_order": 1
  },
  {
    "id": "cafeteria",
    "category_id": "gastronomia",
    "label": "Cafetería",
    "sort_order": 2
  },
  {
    "id": "bar",
    "category_id": "gastronomia",
    "label": "Bar",
    "sort_order": 3
  },
  {
    "id": "pizzeria",
    "category_id": "gastronomia",
    "label": "Pizzería",
    "sort_order": 4
  },
  {
    "id": "parrilla",
    "category_id": "gastronomia",
    "label": "Parrilla",
    "sort_order": 5
  },
  {
    "id": "rotiseria",
    "category_id": "gastronomia",
    "label": "Rotisería",
    "sort_order": 6
  },
  {
    "id": "menu-serrano",
    "category_id": "gastronomia",
    "label": "Menu Serrano",
    "sort_order": 7
  },
  {
    "id": "bna",
    "category_id": "gastronomia",
    "label": "BNA",
    "sort_order": 8
  },
  {
    "id": "cabanas",
    "category_id": "alojamiento",
    "label": "Cabañas",
    "sort_order": 1
  },
  {
    "id": "complejo",
    "category_id": "alojamiento",
    "label": "Complejo",
    "sort_order": 2
  },
  {
    "id": "casa",
    "category_id": "alojamiento",
    "label": "Casa",
    "sort_order": 3
  },
  {
    "id": "apart-hotel",
    "category_id": "alojamiento",
    "label": "Apart Hotel",
    "sort_order": 4
  },
  {
    "id": "hosteria",
    "category_id": "alojamiento",
    "label": "Hostería",
    "sort_order": 5
  },
  {
    "id": "hotel",
    "category_id": "alojamiento",
    "label": "Hotel",
    "sort_order": 6
  },
  {
    "id": "posada",
    "category_id": "alojamiento",
    "label": "Posada",
    "sort_order": 7
  },
  {
    "id": "departamentos",
    "category_id": "alojamiento",
    "label": "Departamentos",
    "sort_order": 8
  },
  {
    "id": "hostal",
    "category_id": "alojamiento",
    "label": "Hostal",
    "sort_order": 9
  }
];
const IMPORT_BUSINESSES = [
  {
    "legacy_id": "complejo-retana",
    "name": "Complejo Retana - Cabañas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": "Cabañas familiares totalmente equipadas, rodeadas de naturaleza serrana, ideales para descansar en pareja o en familia.",
    "address": "Las Catitas y Reina Mora, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "Recepción 8:00 a 22:00"
    },
    "phone": "+54 9 266 000-0001",
    "whatsapp": "+54 9 266 000-0001",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2483,
    "lng": -66.2623,
    "featured": false,
    "open": true,
    "images": [
      "images/comercios/complejo-retana.jpg"
    ]
  },
  {
    "legacy_id": "lunas-y-soles",
    "name": "Lunas y Soles - Cabañas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": "Cabañas de diseño con vista a las sierras, pileta de uso común y desayuno regional incluido.",
    "address": "Santa Rita 559, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "Recepción 9:00 a 21:00"
    },
    "phone": "+54 9 266 000-0002",
    "whatsapp": "+54 9 266 000-0002",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2372,
    "lng": -66.2512,
    "featured": true,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "agua-clara-parador",
    "name": "Agua Clara - Parador",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": "Parador con habitaciones frente al lago y acceso directo a la costa para disfrutar del atardecer.",
    "address": "Camino Mirador, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "Abierto todos los días"
    },
    "phone": "+54 9 266 000-0003",
    "whatsapp": "+54 9 266 000-0003",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2261,
    "lng": -66.2701,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "lo-de-vito",
    "name": "Lo de Vito",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": "Restaurante con cocina Italiana y ambiente romantico.",
    "address": "Los Paraísos 3171, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "12:00–16:00 y 20:00–00:00"
    },
    "phone": "+5492664495061",
    "whatsapp": "+5492664495061",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.245,
    "lng": -66.259,
    "featured": true,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "agua-clara-cabalgatas",
    "name": "Agua Clara - Travesías y Cabalgatas",
    "category_id": "turismo",
    "subcategory_id": null,
    "description": "Cabalgatas y travesías guiadas por las sierras, para todas las edades y niveles.",
    "address": "Camino Mirador, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "9:00 a 18:00"
    },
    "phone": "+54 9 266 000-0007",
    "whatsapp": "+54 9 266 000-0007",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2417,
    "lng": -66.2557,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-salagria-turismo",
    "name": "La Salagria",
    "category_id": "turismo",
    "subcategory_id": null,
    "description": "Paseos náuticos y actividades recreativas en el dique, alquiler de kayaks y botes a pedal.",
    "address": "Camino Mirador, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "10:00 a 19:00"
    },
    "phone": "+54 9 266 000-0008",
    "whatsapp": "+54 9 266 000-0008",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2306,
    "lng": -66.2746,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "potrero-bike-rental",
    "name": "Potrero Bike Rental",
    "category_id": "turismo",
    "subcategory_id": null,
    "description": "Alquiler de bicicletas para recorrer el circuito del lago a tu ritmo.",
    "address": "Av. del Circuito 900, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "9:00 a 20:00"
    },
    "phone": "+54 9 266 000-0009",
    "whatsapp": "+54 9 266 000-0009",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2195,
    "lng": -66.26350000000001,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "farmacia-potrero",
    "name": "Farmacia Potrero",
    "category_id": "salud",
    "subcategory_id": null,
    "description": "Farmacia con entrega a domicilio y guardia rotativa en temporada alta.",
    "address": "Av. del Circuito 450, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "8:00 a 21:00"
    },
    "phone": "+54 9 266 000-0010",
    "whatsapp": "+54 9 266 000-0010",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2384,
    "lng": -66.2524,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "centro-salud",
    "name": "Centro de Salud Comunitario",
    "category_id": "salud",
    "subcategory_id": null,
    "description": "Atención primaria, vacunación y guardia para urgencias menores.",
    "address": "Calle Los Cardones s/n, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "7:00 a 20:00"
    },
    "phone": "+54 9 266 000-0011",
    "whatsapp": "+54 9 266 000-0011",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2273,
    "lng": -66.2713,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "fuerza-12-store",
    "name": "Fuerza 12 Store - Gym",
    "category_id": "comercios",
    "subcategory_id": null,
    "description": "Indumentaria deportiva, suplementos y accesorios de entrenamiento.",
    "address": "Avenida Circuito y Las Higueras, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "9:00 a 20:00"
    },
    "phone": "+54 9 266 000-0012",
    "whatsapp": "+54 9 266 000-0012",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2462,
    "lng": -66.2602,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "almacen-sierras",
    "name": "Almacén de las Sierras",
    "category_id": "comercios",
    "subcategory_id": null,
    "description": "Productos regionales, dulces artesanales y souvenirs de la zona.",
    "address": "Calle Real 210, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "9:00 a 21:00"
    },
    "phone": "+54 9 266 000-0013",
    "whatsapp": "+54 9 266 000-0013",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2351,
    "lng": -66.2791,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "gomeria-circuito",
    "name": "Gomería El Circuito",
    "category_id": "servicios",
    "subcategory_id": null,
    "description": "Reparación de neumáticos, auxilio mecánico y service básico.",
    "address": "Av. del Circuito 1500, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "8:00 a 19:00"
    },
    "phone": "+54 9 266 000-0014",
    "whatsapp": "+54 9 266 000-0014",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.224,
    "lng": -66.268,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "inmobiliaria-potrero",
    "name": "Inmobiliaria Potrero",
    "category_id": "servicios",
    "subcategory_id": null,
    "description": "Venta y alquiler de propiedades, cabañas y terrenos en la zona.",
    "address": "Calle Real 88, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "9:00 a 18:00"
    },
    "phone": "+54 9 266 000-0015",
    "whatsapp": "+54 9 266 000-0015",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2429,
    "lng": -66.2569,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "nautica-potrero",
    "name": "Náutica Potrero",
    "category_id": "deportes",
    "subcategory_id": null,
    "description": "Alquiler de kayaks, tablas SUP y equipos náuticos para disfrutar del dique.",
    "address": "Costanera del Lago, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "9:00 a 19:00"
    },
    "phone": "+54 9 266 000-0016",
    "whatsapp": "+54 9 266 000-0016",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2318,
    "lng": -66.2758,
    "featured": true,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "fuerza-12-deportes",
    "name": "Fuerza 12 - Entrenamiento Funcional",
    "category_id": "deportes",
    "subcategory_id": null,
    "description": "Clases grupales de entrenamiento funcional al aire libre con vista al lago.",
    "address": "Avenida Circuito y Las Higueras, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "7:00 a 21:00"
    },
    "phone": "+54 9 266 000-0017",
    "whatsapp": "+54 9 266 000-0017",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2207,
    "lng": -66.2647,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "cine-aire-libre",
    "name": "Cine al Aire Libre La Salagria",
    "category_id": "entretenimiento",
    "subcategory_id": null,
    "description": "Proyecciones de cine bajo las estrellas en temporada de verano.",
    "address": "Parque Recreativo La Salagria, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "Vie y Sáb 21:00"
    },
    "phone": "+54 9 266 000-0018",
    "whatsapp": "+54 9 266 000-0018",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2396,
    "lng": -66.2536,
    "featured": true,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "boliche-latitud",
    "name": "Boliche Latitud",
    "category_id": "entretenimiento",
    "subcategory_id": null,
    "description": "Música en vivo y pista de baile los fines de semana en temporada alta.",
    "address": "Av. del Circuito 3000, Potrero de los Funes, San Luis",
    "hours": {
      "texto": "Vie y Sáb 00:00 a 05:00"
    },
    "phone": "+54 9 266 000-0019",
    "whatsapp": "+54 9 266 000-0019",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2285,
    "lng": -66.2725,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "l-agostina",
    "name": "L'agostina",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": "Especialistas en milanesas del Potrero. Restaurante tradicional con ambiente familiar.",
    "address": "Los Ceibos 309",
    "hours": null,
    "phone": "+5492664656035",
    "whatsapp": "+5492664656035",
    "email": null,
    "instagram": "@l_agostinasl",
    "facebook": null,
    "website": null,
    "lat": -33.2396,
    "lng": -66.2536,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "lunamakena",
    "name": "Lunamakena",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": null,
    "address": "Los Membrillos y las higueras",
    "hours": null,
    "phone": "+5492664302349",
    "whatsapp": "+5492664302349",
    "email": null,
    "instagram": "@lunamakenaresto",
    "facebook": null,
    "website": null,
    "lat": -33.2285,
    "lng": -66.2725,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "romanito",
    "name": "Romanito",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": null,
    "address": "Los Paraisos A9",
    "hours": null,
    "phone": "+5492664262354",
    "whatsapp": "+5492664262354",
    "email": null,
    "instagram": "@Romanito_resto",
    "facebook": null,
    "website": null,
    "lat": -33.2474,
    "lng": -66.2614,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "complejo-del-lago",
    "name": "Complejo del Lago",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": "Restaurante con vista panorámica al lago y excelente gastronomía.",
    "address": "a4",
    "hours": null,
    "phone": "+5492664495042",
    "whatsapp": "+5492664495042",
    "email": null,
    "instagram": "@Complejodelagoresto",
    "facebook": null,
    "website": null,
    "lat": -33.2363,
    "lng": -66.2503,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "las-golondrinas",
    "name": "Las Golondrinas",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": "Restaurante tradicional con excelentes platos caseros.",
    "address": "Los Paraisos 450",
    "hours": null,
    "phone": "+5492664681188",
    "whatsapp": "+5492664681188",
    "email": null,
    "instagram": "@Lasgolondrinasrestaurant",
    "facebook": null,
    "website": null,
    "lat": -33.2252,
    "lng": -66.2692,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "casa-blanca",
    "name": "Casa Blanca",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": "Restaurante con cocina de autor y vistas privilegiadas.",
    "address": "Av. del Circuito",
    "hours": null,
    "phone": "+5492664564027",
    "whatsapp": "+5492664564027",
    "email": null,
    "instagram": "@Casablancaresto_",
    "facebook": null,
    "website": null,
    "lat": -33.2441,
    "lng": -66.2581,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "tipico",
    "name": "Tipico",
    "category_id": "gastronomia",
    "subcategory_id": "pizzeria",
    "description": "Pizzería con delivery y variedad de sabores.",
    "address": "a10",
    "hours": null,
    "phone": "+5492664019595",
    "whatsapp": "+5492664019595",
    "email": null,
    "instagram": "@Pizzeria_tipico",
    "facebook": null,
    "website": null,
    "lat": -33.233,
    "lng": -66.277,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "cafe-puntano",
    "name": "Café Puntano",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": "Cafetería con ambiente cálido y variedad de opciones gastronómicas.",
    "address": "Los paraisos 637",
    "hours": null,
    "phone": "+5492664748431",
    "whatsapp": "+5492664748431",
    "email": null,
    "instagram": "@cafepuntano",
    "facebook": null,
    "website": null,
    "lat": -33.2219,
    "lng": -66.2659,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "massanto",
    "name": "Massanto",
    "category_id": "gastronomia",
    "subcategory_id": "cafeteria",
    "description": "Cafetería especializada en alfajores artesanales y café de calidad.",
    "address": "Av. Del Circuito 2560",
    "hours": null,
    "phone": "+5492664615105",
    "whatsapp": "+5492664615105",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2408,
    "lng": -66.2548,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "gin-eternal",
    "name": "Gin Eternal",
    "category_id": "gastronomia",
    "subcategory_id": "bar",
    "description": "La mejor destileria de Gin de Autor del país",
    "address": "Av. Los Paraísos 832",
    "hours": null,
    "phone": "+5492665030552",
    "whatsapp": "+5492665030552",
    "email": null,
    "instagram": "@gineternal",
    "facebook": null,
    "website": null,
    "lat": -33.2297,
    "lng": -66.2737,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "el-bodegon",
    "name": "El Bodegon",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": "Restaurante con cocina casera y ambiente acogedor.",
    "address": "Los paraisos y los plátanos A9",
    "hours": null,
    "phone": "+5492664273276",
    "whatsapp": "+5492664273276",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2186,
    "lng": -66.2626,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "las-canitas",
    "name": "Las Cañitas",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": null,
    "address": "Los Paraísos esq los membrillos",
    "hours": null,
    "phone": "+5492664581690",
    "whatsapp": "+5492664581690",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2375,
    "lng": -66.25150000000001,
    "featured": false,
    "open": false,
    "images": []
  },
  {
    "legacy_id": "parrilla-don-juan",
    "name": "Parrilla Don Juan",
    "category_id": "gastronomia",
    "subcategory_id": "parrilla",
    "description": "Parrilla tradicional con las mejores carnes de la región.",
    "address": "Av. del Circuito del lago S/n",
    "hours": null,
    "phone": "+5492664886777",
    "whatsapp": "+5492664886777",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2264,
    "lng": -66.2704,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "el-malon",
    "name": "El Malon",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": "Restaurante con propuesta gastronómica regional y cerveza artesanal.",
    "address": "a5",
    "hours": null,
    "phone": "+5492664858406",
    "whatsapp": "+5492664858406",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2453,
    "lng": -66.2593,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "inaki",
    "name": "iñaki",
    "category_id": "gastronomia",
    "subcategory_id": "cafeteria",
    "description": "Cafetería con productos artesanales y pastelería.",
    "address": "a12",
    "hours": null,
    "phone": "+5492664847445",
    "whatsapp": "+5492664847445",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2342,
    "lng": -66.2782,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "calixto",
    "name": "Calixto",
    "category_id": "gastronomia",
    "subcategory_id": "resto",
    "description": "Resto café con ambiente moderno y variedad de platos.",
    "address": "a12",
    "hours": null,
    "phone": "+5492664775734",
    "whatsapp": "+5492664775734",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2231,
    "lng": -66.2671,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "abuelito-antonio-cabanas",
    "name": "Abuelito Antonio Cabañas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": null,
    "hours": null,
    "phone": "+5492664678178",
    "whatsapp": "+5492664678178",
    "email": null,
    "instagram": "@abuelitoantoniocabanas",
    "facebook": null,
    "website": null,
    "lat": -33.224681,
    "lng": -66.226895,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "aguamansa-apart-hotel",
    "name": "Aguamansa Apart Hotel",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Ruta N° 18 Camino a El Volcan",
    "hours": null,
    "phone": "+54 266 4851673",
    "whatsapp": "+54 266 4851673",
    "email": "reservas@aguamansasanluis.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.aguamansasanluis.com.ar",
    "lat": -33.2309,
    "lng": -66.2749,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "aitue",
    "name": "Aitue",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Av. del Circuito Esq. Las Lavandas",
    "hours": null,
    "phone": "+54 266 4340442",
    "whatsapp": "+54 266 4340442",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2198,
    "lng": -66.2638,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "ak-tu-lugar",
    "name": "AK Tu Lugar",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Lavandas 195",
    "hours": null,
    "phone": "+54 2657 544490",
    "whatsapp": "+54 2657 544490",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.udaer.org",
    "lat": -33.2387,
    "lng": -66.2527,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "amantea-apart-hotel",
    "name": "Amantea Apart Hotel",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Circuito Lateral Secc 1",
    "hours": null,
    "phone": "+54 911 40447644",
    "whatsapp": "+54 911 40447644",
    "email": "amanteaapart@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.amanteaapart.com.ar",
    "lat": -33.2276,
    "lng": -66.2716,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "antu-kuyen",
    "name": "Antu Kuyen",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Lavandas 420",
    "hours": null,
    "phone": "+54 2656 406128",
    "whatsapp": "+54 2656 406128",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2465,
    "lng": -66.26050000000001,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "apart-altos-de-aliwen",
    "name": "Apart Altos De Aliwen",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": null,
    "hours": null,
    "phone": "+5492665006249",
    "whatsapp": "+5492665006249",
    "email": null,
    "instagram": "@altosdealiwen",
    "facebook": null,
    "website": null,
    "lat": -33.2354,
    "lng": -66.2794,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "aroma-de-potrero",
    "name": "Aroma de Potrero",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Arándanos 10",
    "hours": null,
    "phone": "+54 2665 044950",
    "whatsapp": "+54 2665 044950",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2243,
    "lng": -66.2683,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "augurios-del-sol-2",
    "name": "Augurios del Sol 2",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Siete Colores y Colibri",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2432,
    "lng": -66.2572,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "ayres-de-funes",
    "name": "Ayres de Funes",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Av. del Circuito 2920",
    "hours": null,
    "phone": "+54 2664 893799",
    "whatsapp": "+54 2664 893799",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.ayresdefunes.com.ar",
    "lat": -33.2321,
    "lng": -66.2761,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "balcones-del-lago",
    "name": "Balcones del Lago",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Barrio La Agripina",
    "hours": null,
    "phone": "+54 2664 842205",
    "whatsapp": "+54 2664 842205",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.221,
    "lng": -66.265,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "bella-vista",
    "name": "Bella Vista",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Manzanos 180",
    "hours": null,
    "phone": "+54 9 266 4348132",
    "whatsapp": "+54 9 266 4348132",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2399,
    "lng": -66.2539,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "brisa-del-lago",
    "name": "Brisa del Lago",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Santa Rita 84",
    "hours": null,
    "phone": "+54 2664 226521",
    "whatsapp": "+54 2664 226521",
    "email": "brisadellago@hotmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.brisadellago.com.ar",
    "lat": -33.2288,
    "lng": -66.2728,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "brisa-serrana",
    "name": "Brisa Serrana",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Carpinteros 120",
    "hours": null,
    "phone": "+54 266 4246617",
    "whatsapp": "+54 266 4246617",
    "email": "federicoclosa@hotmail.com",
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2477,
    "lng": -66.2617,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "cabanas-holtfor",
    "name": "Cabañas Holtfor",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Espinillos 434",
    "hours": null,
    "phone": "+54 9 11 61471132",
    "whatsapp": "+54 9 11 61471132",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "https://holtfor.wixsite.com/alojamiento",
    "lat": -33.2366,
    "lng": -66.2506,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "cabanas-inaki-anexo-cafeteria",
    "name": "Cabañas Iñaki + Anexo Cafetería",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Horneros 3183",
    "hours": null,
    "phone": "+54 2664 869423",
    "whatsapp": "+54 2664 869423",
    "email": "reservas@losinaki.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.losinaki.com.ar",
    "lat": -33.2255,
    "lng": -66.2695,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "cabanas-lucero",
    "name": "Cabañas Lucero",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Arándanos 45",
    "hours": null,
    "phone": "+54 11 54297051",
    "whatsapp": "+54 11 54297051",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2444,
    "lng": -66.2584,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "casa-alquiler-por-dia",
    "name": "Casa Alquiler por Día",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "24 Viv Mza A Casa 24 Potrero",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2333,
    "lng": -66.2773,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "casa-de-las-flores",
    "name": "Casa de las Flores",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Violetas 178 (entre Las Rosas y Las Hortensias), Potrero de los Funes",
    "hours": null,
    "phone": "5492664707182",
    "whatsapp": "5492664707182",
    "email": "josuko16@gmail.com",
    "instagram": "@lacasadelasflorespotrero",
    "facebook": null,
    "website": "https://www.lacasadelasflorespotrerodelosfunes.com.ar",
    "lat": -33.2222,
    "lng": -66.2662,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "casa-majo",
    "name": "Casa Majo",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Santa Rita 481",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2411,
    "lng": -66.2551,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "castillo-de-sol",
    "name": "Castillo de sol",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Circuito del Lago 3360",
    "hours": null,
    "phone": "+54 266 4559847",
    "whatsapp": "+54 266 4559847",
    "email": "castillo.desol@yahoo.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.castillodesol.com.ar",
    "lat": -33.23,
    "lng": -66.274,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "cefiro",
    "name": "Cefiro",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Loteo Piquillem al Lado de Cabañas Elsa & Fred",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "https://www.cabaniascefiro.com.ar",
    "lat": -33.2189,
    "lng": -66.2629,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "claro-de-luna",
    "name": "Claro de Luna",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Cortaderas 355 – Esquina Las Lavandas A3",
    "hours": null,
    "phone": "+54 2664 553033",
    "whatsapp": "+54 2664 553033",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.argentinaturismo.com.ar/clarodeluna/",
    "lat": -33.2378,
    "lng": -66.2518,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "colores-de-los-funes",
    "name": "Colores de los Funes",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Circuito del Lago y Río s/n",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2267,
    "lng": -66.2707,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "complejo-el-mirador",
    "name": "Complejo El Mirador",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Av. del Circuito Esq. Las Catalpas",
    "hours": null,
    "phone": "+54 2664 668764",
    "whatsapp": "+54 2664 668764",
    "email": "info@complejodelmirador.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.complejodelmirador.com.ar",
    "lat": -33.2456,
    "lng": -66.2596,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "cumelem",
    "name": "Cumelem",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Almendros 902",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2345,
    "lng": -66.2785,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "del-duende",
    "name": "Del Duende",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Eucaliptos 150",
    "hours": null,
    "phone": "+54 2901 469068",
    "whatsapp": "+54 2901 469068",
    "email": "info@cabanasdelduende.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.cabanasdelduende.com/",
    "lat": -33.2234,
    "lng": -66.2674,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "del-fuego",
    "name": "Del Fuego",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Eucaliptos 259",
    "hours": null,
    "phone": "+54 2901 468247",
    "whatsapp": "+54 2901 468247",
    "email": "joseciccone66@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.cabanasdelfuego.wordpress.com",
    "lat": -33.2423,
    "lng": -66.2563,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "destello-del-lago",
    "name": "Destello del Lago",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Av. del Circuito E/ A3 y A4",
    "hours": null,
    "phone": "+54 2664 834995",
    "whatsapp": "+54 2664 834995",
    "email": "info@destellosdellago.com.ar",
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2312,
    "lng": -66.2752,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "dona-emilia",
    "name": "Doña Emilia",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Eucaliptos Bis S/N",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2201,
    "lng": -66.2641,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "el-colibri",
    "name": "El Colibri",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Castaños 33",
    "hours": null,
    "phone": "+54 9 2664 58-4169",
    "whatsapp": "+54 9 2664 58-4169",
    "email": "elcolibripotrero@yahoo.com",
    "instagram": null,
    "facebook": "Cabañas-El-Colibri-778484572346293",
    "website": null,
    "lat": -33.239,
    "lng": -66.253,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "el-crepusculo",
    "name": "El Crepúsculo",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Ciruelos 645",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "https://www.facebook.com/p/El-Crepusculo-caba%C3%B1as-100080100693330/",
    "lat": -33.2279,
    "lng": -66.2719,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "el-fin-del-afan",
    "name": "El Fin del Afán",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Espinillos s/n",
    "hours": null,
    "phone": "+54 9 291 645-6061",
    "whatsapp": "+54 9 291 645-6061",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "https://www.instagram.com/el.fin.del.afan/",
    "lat": -33.2468,
    "lng": -66.2608,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "el-nogal",
    "name": "El Nogal",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Cesar Bustos s/n",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2357,
    "lng": -66.2797,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "el-reparo",
    "name": "El Reparo",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Piquillines Lote 4",
    "hours": null,
    "phone": "+54 2664 709284",
    "whatsapp": "+54 2664 709284",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "https://udaer.org/",
    "lat": -33.2246,
    "lng": -66.2686,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "el-triunfo-apart",
    "name": "El Triunfo Apart",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Margaritas y Cortaderas A5",
    "hours": null,
    "phone": "+54 2664 266538",
    "whatsapp": "+54 2664 266538",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.udaer.org/",
    "lat": -33.2435,
    "lng": -66.25750000000001,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "encanto-puntano",
    "name": "Encanto Puntano",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Arandanos 15",
    "hours": null,
    "phone": "+54 9 2664 654244",
    "whatsapp": "+54 9 2664 654244",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2324,
    "lng": -66.2764,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "estacion-potrero",
    "name": "Estación Potrero",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Espinillos 438",
    "hours": null,
    "phone": "+54 9 11 31023001",
    "whatsapp": "+54 9 11 31023001",
    "email": "estacionpotrero@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "www.estacionpotrero.com",
    "lat": -33.2213,
    "lng": -66.2653,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "eureka",
    "name": "Eureka",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Piquillines 3800",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2402,
    "lng": -66.2542,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "gemas-del-lago",
    "name": "Gemas del Lago",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Eucaliptos S/N A14",
    "hours": null,
    "phone": "+54 2664 631687",
    "whatsapp": "+54 2664 631687",
    "email": "liclauramai2@hotmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.gemasdellago.com.ar",
    "lat": -33.2291,
    "lng": -66.2731,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "hosteria-lihuen",
    "name": "Hostería Lihuen",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Caléndulas 299",
    "hours": null,
    "phone": "+54 2664 495275",
    "whatsapp": "+54 2664 495275",
    "email": "hosterialihuen@coopenetlujan.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.hotelesdeargentina.com.ar/san-luis/potrero-de-los-funes/hosterias-1-estrella/lihuen",
    "lat": -33.248,
    "lng": -66.262,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "hotel-potrero-de-los-funes",
    "name": "Hotel Potrero de los Funes",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Ruta 18 Km. 16",
    "hours": null,
    "phone": "+54 2664 440038",
    "whatsapp": "+54 2664 440038",
    "email": "reservas@hotelpotrero.sanluis.gov.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.hotelpotrero.sanluis.gov.ar/",
    "lat": -33.2369,
    "lng": -66.2509,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "hotel-puntano",
    "name": "Hotel Puntano",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Paraisos 637",
    "hours": null,
    "phone": "+54 9 2664 74-8431",
    "whatsapp": "+54 9 2664 74-8431",
    "email": null,
    "instagram": "@hotelpuntano",
    "facebook": null,
    "website": null,
    "lat": -33.219109,
    "lng": -66.226358,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "koba",
    "name": "Koba",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Piquillines 3540",
    "hours": null,
    "phone": "+54 2665 004996",
    "whatsapp": "+54 2665 004996",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2447,
    "lng": -66.2587,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "kume",
    "name": "Kume",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Piquillines 425",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2336,
    "lng": -66.2776,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-casa-de-mune",
    "name": "La Casa de Muñe",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Mza G Casa 7 Bº 69 Ara Gral Belgrano",
    "hours": null,
    "phone": "+54 2664 649875",
    "whatsapp": "+54 2664 649875",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2225,
    "lng": -66.2665,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-casa-del-tata-hostal",
    "name": "La Casa del Tata - Hostal",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Violetas 259",
    "hours": null,
    "phone": "+54 2664 209889",
    "whatsapp": "+54 2664 209889",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "https://udaer.org/",
    "lat": -33.2414,
    "lng": -66.2554,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-colina",
    "name": "La Colina",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Zona Boxes",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2303,
    "lng": -66.2743,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-gringa",
    "name": "La Gringa",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Paraísos 186",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2192,
    "lng": -66.2632,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-lomita",
    "name": "La Lomita",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Paraísos y Pje. Las Calandrias",
    "hours": null,
    "phone": "+54 11 22920254",
    "whatsapp": "+54 11 22920254",
    "email": "complejolalomitaok@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "https://udaer.org/",
    "lat": -33.2381,
    "lng": -66.2521,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-mamalia-casa-en-alquiler",
    "name": "La Mamalia - Casa en Alquiler",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Bº Ara Gral. Belgrano Mza.G C.2",
    "hours": null,
    "phone": "+54 2664 649875",
    "whatsapp": "+54 2664 649875",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.227,
    "lng": -66.271,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-norma-casa-en-alquiler",
    "name": "La Norma - Casa en Alquiler",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Mza G Casa 4 B° Ara Gral Belgrano",
    "hours": null,
    "phone": "+54 2664 649875",
    "whatsapp": "+54 2664 649875",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2459,
    "lng": -66.2599,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-quebrada-apart-hotel",
    "name": "La Quebrada Apart Hotel",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Ciruelos y Los Peros",
    "hours": null,
    "phone": "+54 2664 019664",
    "whatsapp": "+54 2664 019664",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2348,
    "lng": -66.2788,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "la-soleada",
    "name": "La Soleada",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Ciruelos 648",
    "hours": null,
    "phone": "+54 11 41939061",
    "whatsapp": "+54 11 41939061",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "https://www.udaer.org/",
    "lat": -33.2237,
    "lng": -66.2677,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "las-acacias",
    "name": "Las Acacias",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Guindos 2197",
    "hours": null,
    "phone": "+54 2665 048624",
    "whatsapp": "+54 2665 048624",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2426,
    "lng": -66.2566,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "las-encinas",
    "name": "Las Encinas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Santa Rita Esq. Jazmines",
    "hours": null,
    "phone": "+54 2664 495450",
    "whatsapp": "+54 2664 495450",
    "email": "info@lasencinas.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://lasencinas.com.ar/",
    "lat": -33.2315,
    "lng": -66.2755,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "las-mercedes",
    "name": "Las Mercedes",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Av. del Circuito y Cost. Los Arenales",
    "hours": null,
    "phone": "+54 2396 634651",
    "whatsapp": "+54 2396 634651",
    "email": "cabaniaslasmercedes@hotmail.com",
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2204,
    "lng": -66.2644,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "las-piedras",
    "name": "Las Piedras",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Damascos 453",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2393,
    "lng": -66.2533,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "las-torcazas",
    "name": "Las Torcazas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Paraísos 20",
    "hours": null,
    "phone": "+54 11 65771960",
    "whatsapp": "+54 11 65771960",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "https://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2282,
    "lng": -66.2722,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "lo-de-esther",
    "name": "Lo de Esther",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Barrio 69 Viv. Mza. B / Casa 11",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2471,
    "lng": -66.2611,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "los-alelies",
    "name": "Los Alelíes",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Alelíes 185 Esq. Las Petunias",
    "hours": null,
    "phone": "+54 2604 632629",
    "whatsapp": "+54 2604 632629",
    "email": "complejolosalelies@hotmail.com",
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.236,
    "lng": -66.28,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "los-arroyitos",
    "name": "Los Arroyitos",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Ruta 18 Km 20",
    "hours": null,
    "phone": "+54 2664 554776",
    "whatsapp": "+54 2664 554776",
    "email": "losarroyitos.pt@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.losarroyitos.com",
    "lat": -33.2249,
    "lng": -66.2689,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "los-fresnos",
    "name": "Los Fresnos",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Tipas 2859",
    "hours": null,
    "phone": "+54 2664 372291",
    "whatsapp": "+54 2664 372291",
    "email": "losfresnos-potrero@hotmail.com",
    "instagram": null,
    "facebook": null,
    "website": "https://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2438,
    "lng": -66.2578,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "los-molles",
    "name": "Los Molles",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Molles 450",
    "hours": null,
    "phone": "+54 2664 659027",
    "whatsapp": "+54 2664 659027",
    "email": "Complejolosmolles@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.complejolosmolles.com.ar/",
    "lat": -33.2327,
    "lng": -66.2767,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "los-naranjos",
    "name": "Los Naranjos",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Guindos 2191",
    "hours": null,
    "phone": "+54 2664 205210",
    "whatsapp": "+54 2664 205210",
    "email": "losnaranjosdepotrero@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.potrerofunes.wixsite.com/hosterialosnaranjos",
    "lat": -33.2216,
    "lng": -66.2656,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "los-paraisos",
    "name": "Los Paraísos",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Av. del Circuito 3236",
    "hours": null,
    "phone": "+54 2664 219921",
    "whatsapp": "+54 2664 219921",
    "email": "carlosvcaballero@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2405,
    "lng": -66.25450000000001,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "los-pinos-1",
    "name": "Los Pinos 1",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Pinos 132",
    "hours": null,
    "phone": "+54 2664 678680",
    "whatsapp": "+54 2664 678680",
    "email": "fabiomuller76@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2294,
    "lng": -66.2734,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "ludmar",
    "name": "LudMar",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Violetas 98 y Las Rosas",
    "hours": null,
    "phone": "+54 2664540187",
    "whatsapp": "+54 2664540187",
    "email": "ludmar@hotmail.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.ludmar.com.ar/",
    "lat": -33.2483,
    "lng": -66.2623,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "lunamakena-2",
    "name": "Lunamakena",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Membrillos 83",
    "hours": null,
    "phone": "+54 266 4302349",
    "whatsapp": "+54 266 4302349",
    "email": "administracion@lunamakena.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "https://lunamakena.com/",
    "lat": -33.2372,
    "lng": -66.2512,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "lunas-y-soles-2",
    "name": "Lunas y Soles",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Santa Rita 559",
    "hours": null,
    "phone": "+54 2664 223030",
    "whatsapp": "+54 2664 223030",
    "email": "joragueva@hotmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.cabanaslunasysoles.webnode.page/",
    "lat": -33.2261,
    "lng": -66.2701,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "mirando-al-valle",
    "name": "Mirando al Valle",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Eucaliptos 240",
    "hours": null,
    "phone": "+54 2664 649875",
    "whatsapp": "+54 2664 649875",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.udaer.org",
    "lat": -33.245,
    "lng": -66.259,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "molinos-de-vientos",
    "name": "Molinos de Vientos",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Carpinteros 18",
    "hours": null,
    "phone": "+54 2664 209889",
    "whatsapp": "+54 2664 209889",
    "email": "molinosdevientos.sl@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2339,
    "lng": -66.2779,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "montearena",
    "name": "Montearena",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Manantiales 383",
    "hours": null,
    "phone": "+54 2664 888901",
    "whatsapp": "+54 2664 888901",
    "email": "montearena.sl@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.udaer.org/",
    "lat": -33.2228,
    "lng": -66.2668,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "munay",
    "name": "Munay",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Eucaliptos S/N (Los Manantiales)",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2417,
    "lng": -66.2557,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "murmullo-del-rio",
    "name": "Murmullo del Rio",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Rey del Bosque y Cesar Bustos",
    "hours": null,
    "phone": "+54 2664 581080",
    "whatsapp": "+54 2664 581080",
    "email": "info@murmullodelrio.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.murmullodelrio.com/",
    "lat": -33.2306,
    "lng": -66.2746,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "naife",
    "name": "Naife",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Santa Rita S/N",
    "hours": null,
    "phone": "+54 2664 731025",
    "whatsapp": "+54 2664 731025",
    "email": "Naifeolivares6@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2195,
    "lng": -66.26350000000001,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "oasis-apart",
    "name": "Oasis Apart",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Ruta 18km 20 Paraje Los Arroyitos",
    "hours": null,
    "phone": "+54 266 4169959",
    "whatsapp": "+54 266 4169959",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "https://www.instagram.com/sierrasoasis_apart/",
    "lat": -33.2384,
    "lng": -66.2524,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "oliber-cabanas",
    "name": "Oliber Cabañas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "A 14 - Los Eucaliptos",
    "hours": null,
    "phone": "+54 11 52484474",
    "whatsapp": "+54 11 52484474",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.udaer.org",
    "lat": -33.2273,
    "lng": -66.2713,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "pauvalen-1-y-2",
    "name": "Pauvalen 1 y 2",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Violetas 1252",
    "hours": null,
    "phone": "+54 261 6589302",
    "whatsapp": "+54 261 6589302",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.pauvalen.com.ar/",
    "lat": -33.2462,
    "lng": -66.2602,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "pisco-yaku",
    "name": "Pisco Yaku",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Ciruelos 331",
    "hours": null,
    "phone": "+54 2664 571344",
    "whatsapp": "+54 2664 571344",
    "email": "info@piscoyaku.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.piscoyaku.com.ar",
    "lat": -33.2351,
    "lng": -66.2791,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "posada-spa-terrazas",
    "name": "Posada Spa Terrazas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Av. Circuito del Lago y Río, Potrero de los Funes",
    "hours": null,
    "phone": "0266 154777751",
    "whatsapp": "0266 154777751",
    "email": "posadaspaterrazas@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "https://www.terrazasdepotrero.com.ar/",
    "lat": -33.224,
    "lng": -66.268,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "posada-valle-del-sol",
    "name": "Posada Valle del Sol",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Membrillos S/N",
    "hours": null,
    "phone": "+54 2664 368288",
    "whatsapp": "+54 2664 368288",
    "email": "posadavalledelsol@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.posadavalledelsol.com.ar",
    "lat": -33.2429,
    "lng": -66.2569,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "pueblo-de-jesus",
    "name": "Pueblo de Jesús",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Fucsias 707",
    "hours": null,
    "phone": "+54 2664 546507",
    "whatsapp": "+54 2664 546507",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2318,
    "lng": -66.2758,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "quela",
    "name": "Quela",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Violetas 47",
    "hours": null,
    "phone": "+54 2664 580392",
    "whatsapp": "+54 2664 580392",
    "email": "info@complejoquela.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.complejoquela.com",
    "lat": -33.2207,
    "lng": -66.2647,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "ramadas",
    "name": "Ramadas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Violetas y Los Tulipanes",
    "hours": null,
    "phone": "+54 2664 234529",
    "whatsapp": "+54 2664 234529",
    "email": "complejoramadas@hotmail.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2396,
    "lng": -66.2536,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "ranchito-de-suenos",
    "name": "Ranchito de Sueños",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Acceso 14",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2285,
    "lng": -66.2725,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "retana",
    "name": "Retana",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Reina Mora y Las Catitas",
    "hours": null,
    "phone": "+54 2664 369726",
    "whatsapp": "+54 2664 369726",
    "email": "info@complejoretana.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.complejoretana.com.ar",
    "lat": -33.2474,
    "lng": -66.2614,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "rincon-del-rio",
    "name": "Rincón del Río",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Almendros 113",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2363,
    "lng": -66.2503,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "rincon-potrero",
    "name": "Rincón Potrero",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Violetas 67",
    "hours": null,
    "phone": "+54 2664 338959",
    "whatsapp": "+54 2664 338959",
    "email": "rinconpotrero@yahoo.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2252,
    "lng": -66.2692,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "ruca-kiyen",
    "name": "Ruca Kiyen",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Rey del Bosque 37",
    "hours": null,
    "phone": "+54 2664 869488",
    "whatsapp": "+54 2664 869488",
    "email": "rkiyen@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2441,
    "lng": -66.2581,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "sol-dorado",
    "name": "Sol Dorado",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Horneros 3427",
    "hours": null,
    "phone": "+54 2664 551587",
    "whatsapp": "+54 2664 551587",
    "email": "csoldorado@yahoo.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.233,
    "lng": -66.277,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "solares-de-potrero",
    "name": "Solares de Potrero",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Alisos 45",
    "hours": null,
    "phone": "+54 2664 663410",
    "whatsapp": "+54 2664 663410",
    "email": "solaresdepotrero@hotmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.turismoenpotrerodelosfunes.com/complejos-de-cabaas",
    "lat": -33.2219,
    "lng": -66.2659,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "sololosta-cabanas",
    "name": "Sololosta Cabañas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Paraísos y Los Álamos",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2408,
    "lng": -66.2548,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "tata-y-la-emilia",
    "name": "Tata y la Emilia",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Tulipanes 380",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2297,
    "lng": -66.2737,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "terra-soles",
    "name": "Terra Soles",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Margaritas s/n",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2186,
    "lng": -66.2626,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "tronco-silvestre",
    "name": "Tronco Silvestre",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Reina Mora Lote 8",
    "hours": null,
    "phone": "+54 2664 589087",
    "whatsapp": "+54 2664 589087",
    "email": "complejolostroncossanluis@gmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.complejoslostroncospotrero.com.ar",
    "lat": -33.2375,
    "lng": -66.25150000000001,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "turmalina",
    "name": "Turmalina",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Calle 2 de Abril Mza A Casa 9",
    "hours": null,
    "phone": null,
    "whatsapp": null,
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": null,
    "lat": -33.2264,
    "lng": -66.2704,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "valle-la-vaguada",
    "name": "Valle La Vaguada",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Grateus 69",
    "hours": null,
    "phone": "+54 2267 475169",
    "whatsapp": "+54 2267 475169",
    "email": "reservas@vallelavaguada.com.ar",
    "instagram": null,
    "facebook": null,
    "website": "http://www.vallelavaguada.com.ar",
    "lat": -33.2453,
    "lng": -66.2593,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "villa-king",
    "name": "Villa King",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Las Hortensias y Av del Circuito",
    "hours": null,
    "phone": "+54 2664 660251",
    "whatsapp": "+54 2664 660251",
    "email": "villakins@hotmail.com",
    "instagram": null,
    "facebook": null,
    "website": "http://www.villakins.com.ar/",
    "lat": -33.2342,
    "lng": -66.2782,
    "featured": false,
    "open": true,
    "images": []
  },
  {
    "legacy_id": "villa-las-lomas",
    "name": "Villa Las Lomas",
    "category_id": "alojamiento",
    "subcategory_id": null,
    "description": null,
    "address": "Los Espinillos Parcela 441",
    "hours": null,
    "phone": "+54 351 2241661",
    "whatsapp": "+54 351 2241661",
    "email": null,
    "instagram": null,
    "facebook": null,
    "website": "http://www.villalaslomas.wixsite.com/misitio/contactos",
    "lat": -33.2231,
    "lng": -66.2671,
    "featured": false,
    "open": true,
    "images": []
  }
];
